export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED';

export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';

export const USER_QUEUE_SUCCESS = 'USER_QUEUE_SUCCESS';
export const USER_QUEUE_FAILED = 'USER_QUEUE_FAILED';

export const AAD_LOGIN_ = 'AAD_LOGIN';
export const AAD_LOGOUT_SUCCESS = 'AAD_LOGOUT_SUCCESS';
export const AAD_LOGIN = 'AAD_LOGIN';
export const AAD_LOGOUT_FAILED = 'AAD_LOGOUT_FAILED';

export const SET_REDIRECT_REFERRER = 'SET_REDIRECT_REFERRER';
export const REMOVE_REDIRECT_REFERRER = 'REMOVE_REDIRECT_REFERRER';

export const SET_REDIRECT_PATHNAME = 'SET_REDIRECT_PATHNAME';
export const REMOVE_REDIRECT_PATHNAME = 'REMOVE_REDIRECT_PATHNAME';

export const USER_APPROVE_SUCCESS = 'USER_APPROVE_SUCCESS';
export const USER_APPROVE_FAILED = 'USER_APPROVE_FAILED';

export const USER_REJECT_SUCCESS = 'USER_APPROVE_SUCCESS';
export const USER_REJECT_FAILED = 'USER_APPROVE_FAILED';

export const USER_QUEUE_UPDATE_SUCCESS = 'USER_QUEUE_UPDATE_SUCCESS';
export const USER_QUEUE_UPDATE_FAILED = 'USER_QUEUE_UPDATE_FAILED';

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';

export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAILED = 'USER_UPDATE_PROFILE_FAILED';

export const USER_QUEUE_INCREMENT = 'USER_QUEUE_INCREMENT';
export const USER_QUEUE_DECREMENT = 'USER_QUEUE_DECREMENT';
export const SET_TABLE_FILTER_MANAGE_USER_QUEUE =
  'SET_TABLE_FILTER_MANAGE_USER_QUEUE';

export const SET_FORM_VALUES_MANAGE_USER = 'SET_FORM_VALUES_MANAGE_USER';
export const SET_FORM_VALUES_MANAGE_USER_QUEUE =
  'SET_FORM_VALUES_MANAGE_USER_QUEUE';

export const USER_QUEUE_TOTAL_PAGES = 'USER_QUEUE_TOTAL_PAGES';

export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_FAILED = 'GET_CUSTOMERS_FAILED';

export const GET_FACILITIES_SUCCESS = 'GET_FACILITIES_SUCCESS';
export const GET_FACILITIES_FAILED = 'GET_FACILITIES_FAILED';

export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_UPDATE_FAILED = 'CUSTOMER_UPDATE_FAILED';

export const FACILITY_UPDATE_SUCCESS = 'FACILITY_UPDATE_SUCCESS';
export const FACILITY_UPDATE_FAILED = 'FACILITY_UPDATE_FAILED';

export const CLOSE_ALL_MODALS = 'CLOSE_ALL_MODALS';
export const TOGGLE_MODAL_EDIT_QUEUE_USER = 'TOGGLE_MODAL_EDIT_QUEUE_USER';
export const TOGGLE_MODAL_EDIT_USER = 'TOGGLE_MODAL_EDIT_USER';
export const TOGGLE_MODAL_EDIT_CUSTOMER = 'TOGGLE_MODAL_EDIT_CUSTOMER';
export const TOGGLE_MODAL_EDIT_FACILITY = 'TOGGLE_MODAL_EDIT_FACILITY';
export const TOGGLE_MODAL_EDIT_PROFILE = 'TOGGLE_MODAL_EDIT_PROFILE';
export const TOGGLE_MODAL_SECURITY_FUNCTIONS =
  'TOGGLE_MODAL_SECURITY_FUNCTIONS';

export const USER_MANAGE_SUCCESS = 'USER_MANAGE_SUCCESS';
export const USER_MANAGE_FAILED = 'USER_MANAGE_FAILED';
export const USER_MANAGE_INCREMENT = 'USER_MANAGE_INCREMENT';
export const USER_MANAGE_DECREMENT = 'USER_MANAGE_DECREMENT';
export const USER_MANAGE_TOTAL_PAGES = 'USER_MANAGE_TOTAL_PAGES';
export const SET_TABLE_FILTER_MANAGE_USER = 'SET_TABLE_FILTER_MANAGE_USER';

// TEAM
export const TEAM_MANAGE_SUCCESS = 'TEAM_MANAGE_SUCCESS';
export const TEAM_MANAGE_FAILED = 'TEAM_MANAGE_FAILED';
export const TEAM_MANAGE_INCREMENT = 'TEAM_MANAGE_INCREMENT';
export const TEAM_MANAGE_DECREMENT = 'TEAM_MANAGE_DECREMENT';
export const TEAM_MANAGE_TOTAL_PAGES = 'TEAM_MANAGE_TOTAL_PAGES';
export const TEAM_UPDATE_SUCCESS = 'TEAM_UPDATE_SUCCESS';
export const TEAM_UPDATE_FAILED = 'TEAM_UPDATE_FAILED';
export const TEAM_DELETE_SUCCESS = 'TEAM_DELETE_SUCCESS';
export const TEAM_DELETE_FAILED = 'TEAM_DELETE_FAILED';
export const TEAM_SAVE_SUCCESS = 'TEAM_SAVE_SUCCESS';
export const TEAM_SAVE_FAILED = 'TEAM_SAVE_FAILED';
export const TOGGLE_MODAL_EDIT_TEAM = 'TOGGLE_MODAL_EDIT_TEAM';
export const SET_TABLE_FILTER_MANAGE_TEAM = 'SET_TABLE_FILTER_MANAGE_TEAM';

// inventory
export const GET_INVENTORY_SUCCESS = 'GET_INVENTORY_SUCCESS';
export const GET_INVENTORY_FAILED = 'GET_INVENTORY_FAILED';
export const INVENTORY_INCREMENT = 'INVENTORY_INCREMENT';
export const INVENTORY_DECREMENT = 'INVENTORY_DECREMENT';
export const INVENTORY_TOTAL_PAGES = 'INVENTORY_TOTAL_PAGES';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAILED = 'PRODUCT_UPDATE_FAILED';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAILED = 'PRODUCT_ADD_FAILED';
export const PRODUCT_MERGE_SUCCESS = 'PRODUCT_MERGE_SUCCESS';
export const PRODUCT_MERGE_FAILED = 'PRODUCT_MERGE_FAILED';
export const TOGGLE_MODAL_EDIT_PRODUCT = 'TOGGLE_MODAL_EDIT_PRODUCT';
export const GET_PRODUCT_INFO_SUCCESS = 'GET_PRODUCT_INFO_SUCCESS';
export const UPDATE_PRODUCT_INFO_SUCCESS = 'UPDATE_PRODUCT_INFO_SUCCESS';
export const GET_PRODUCT_INFO_FAILED = 'GET_PRODUCT_INFO_FAILED';
export const SET_SELECTED_FACILITY = 'SET_SELECTED_FACILITY';
export const INSTALL_UPDATE_SUCCESS = 'INSTALL_UPDATE_SUCCESS';
export const INSTALL_UPDATE_FAILED = 'INSTALL_UPDATE_FAILED';
export const INSTALL_ADD_SUCCESS = 'INSTALL_ADD_SUCCESS';
export const INSTALL_ADD_FAILED = 'INSTALL_ADD_FAILED';
export const INSTALL_DELETE_SUCCESS = 'INSTALL_DELETE_SUCCESS';
export const INSTALL_DELETE_FAILED = 'INSTALL_DELETE_FAILED';
export const TOGGLE_MODAL_EDIT_INSTALL = 'TOGGLE_MODAL_EDIT_INSTALL';
export const TOGGLE_MODAL_INSTALL_CONTACT = 'TOGGLE_MODAL_INSTALL_CONTACT';
export const TOGGLE_MODAL_IMPORT_INSTALL = 'TOGGLE_MODAL_IMPORT_INSTALL';
export const IMPORT_INSTALL_SUCCESS = 'IMPORT_INSTALL_SUCCESS';
export const IMPORT_INSTALL_FAILED = 'IMPORT_INSTALL_FAILED';
export const SET_TABLE_FILTER_MANAGE_INVENTORY =
  'SET_TABLE_FILTER_MANAGE_INVENTORY';
export const INSTALL_CONTACT_SUCCESS = 'INSTALL_CONTACT_SUCCESS';
export const INSTALL_CONTACT_FAILED = 'INSTALL_CONTACT_FAILED';
export const TOGGLE_MODAL_SEARCH_NEW_PRODUCTS =
  'TOGGLE_MODAL_SEARCH_NEW_PRODUCTS';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
export const NEW_PRODUCTS_RESET = 'NEW_PRODUCTS_RESET';
export const TOGGLE_MODAL_MP_RESULT = 'TOGGLE_MODAL_MP_RESULT';
export const TOGGLE_MODAL_MP_RESULT_HISTORY = 'TOGGLE_MODAL_MP_RESULT_HISTORY';
export const TOGGLE_MODAL_MP_RESULT_NOTES = 'TOGGLE_MODAL_MP_RESULT_NOTES';
export const TOGGLE_MODAL_MP_RESULT_ADD = 'TOGGLE_MODAL_MP_RESULT_ADD';

// shopping cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const DECREASE_FROM_CART = 'DECREASE_FROM_CART';
export const UPDATE_QUANTITY_CART = 'UPDATE_QUANTITY_CART';

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_TRAINING_SUCCESS = 'CHECKOUT_TRAINING_SUCCESS';
export const CHECKOUT_TRAINING_FAILED = 'CHECKOUT_TRAINING_FAILED';
export const CHECKOUT_INVENTORY_SUCCESS = 'CHECKOUT_INVENTORY_SUCCESS';
export const CHECKOUT_INVENTORY_FAILED = 'CHECKOUT_INVENTORY_FAILED';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const TOGGLE_MODAL_SHOPPING_CART_TRAINING =
  'TOGGLE_MODAL_SHOPPING_CART_TRAINING';
export const TOGGLE_MODAL_SHOPPING_CART_INVENTORY =
  'TOGGLE_MODAL_SHOPPING_CART_INVENTORY';
export const GET_PURCHASED_TRAINING_SUCCESS = 'GET_PURCHASED_TRAINING_SUCCESS';
export const GET_PURCHASED_TRAINING_FAILED = 'GET_PURCHASED_TRAINING_FAILED';

// product queue
export const PRODUCT_QUEUE_SUCCESS = 'PRODUCT_QUEUE_SUCCESS';
export const PRODUCT_QUEUE_FAILED = 'PRODUCT_QUEUE_FAILED';

export const PRODUCT_APPROVE_SUCCESS = 'PRODUCT_APPROVE_SUCCESS';
export const PRODUCT_APPROVE_FAILED = 'PRODUCT_APPROVE_FAILED';

export const PRODUCT_REJECT_SUCCESS = 'PRODUCT_APPROVE_SUCCESS';
export const PRODUCT_REJECT_FAILED = 'PRODUCT_APPROVE_FAILED';

export const PRODUCT_QUEUE_TOTAL_PAGES = 'PRODUCT_QUEUE_TOTAL_PAGES';
export const TOGGLE_MODAL_APPROVE_PRODUCT = 'TOGGLE_MODAL_APPROVE_PRODUCT';
export const SET_TABLE_FILTER_MANAGE_PRODUCT_QUEUE =
  'SET_TABLE_FILTER_MANAGE_PRODUCT_QUEUE';

// manage jobs
export const JOB_MANAGE_SUCCESS = 'JOB_MANAGE_SUCCESS';
export const JOB_MANAGE_FAILED = 'JOB_MANAGE_FAILED';
export const JOB_UPDATE_SUCCESS = 'JOB_UPDATE_SUCCESS';
export const JOB_UPDATE_FAILED = 'JOB_UPDATE_FAILED';
export const JOB_ADD_SUCCESS = 'JOB_ADD_SUCCESS';
export const JOB_ADD_FAILED = 'JOB_ADD_FAILED';
export const GET_FSE_SUCCESS = 'GET_FSE_SUCCESS';
export const GET_FSE_FAILED = 'GET_FSE_FAILED';
export const JOB_MANAGE_TOTAL_PAGES = 'JOB_MANAGE_TOTAL_PAGES';
export const SET_TABLE_FILTER_MANAGE_JOB = 'SET_TABLE_FILTER_MANAGE_JOB';
export const TOGGLE_MODAL_EDIT_JOB = 'TOGGLE_MODAL_EDIT_JOB';
export const SET_FORM_VALUES_MANAGE_JOB = 'SET_FORM_VALUES_MANAGE_JOB';
export const UPDATE_FORM_VALUES_MANAGE_JOB = 'UPDATE_FORM_VALUES_MANAGE_JOB';
export const SET_SELECTED_JOB_MANAGE_JOB = 'SET_SELECTED_JOB_MANAGE_JOB';
export const CLEAR_SELECTED_JOB_MANAGE_JOB = 'CLEAR_SELECTED_JOB_MANAGE_JOB';

// manage locations
export const LOCATION_MANAGE_SUCCESS = 'LOCATION_MANAGE_SUCCESS';
export const LOCATION_MANAGE_FAILED = 'LOCATION_MANAGE_FAILED';
export const LOCATION_UPDATE_SUCCESS = 'LOCATION_UPDATE_SUCCESS';
export const LOCATION_UPDATE_FAILED = 'LOCATION_UPDATE_FAILED';
export const LOCATION_ADD_SUCCESS = 'LOCATION_ADD_SUCCESS';
export const LOCATION_ADD_FAILED = 'LOCATION_ADD_FAILED';
export const LOCATION_DELETE_SUCCESS = 'LOCATION_DELETE_SUCCESS';
export const LOCATION_DELETE_FAILED = 'LOCATION_DELETE_FAILED';
export const LOCATION_MANAGE_TOTAL_PAGES = 'LOCATION_MANAGE_TOTAL_PAGES';
export const SET_TABLE_FILTER_MANAGE_LOCATION =
  'SET_TABLE_FILTER_MANAGE_LOCATION';
export const TOGGLE_MODAL_EDIT_LOCATION = 'TOGGLE_MODAL_EDIT_LOCATION';
export const SET_VISIBLE_LOCATIONS = 'SET_VISIBLE_LOCATIONS';

/*
* Training Actions
*/
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSES_FAILED = 'LOAD_COURSES_FAILED';
export const LOAD_LESSONS_SUCCESS = 'LOAD_LESSONS_SUCCESS';
export const LOAD_LESSONS_FAILED = 'LOAD_LESSONS_FAILED';
export const LOAD_LESSON = 'LOAD_LESSON';
export const LOAD_QUIZZES_SUCCESS = 'LOAD_QUIZZES_SUCCESS';
export const LOAD_QUIZZES_FAILED = 'LOAD_QUIZZES_FAILED';
export const LOAD_QUIZ = 'LOAD_QUIZ';
export const LOAD_QUIZZES_BY_LESSON_SUCCESS = 'LOAD_QUIZZES_BY_LESSON_SUCCESS';
export const LOAD_QUIZZES_BY_LESSON_FAILED = 'LOAD_QUIZZES_BY_LESSON_FAILED';

export const GET_ALL_LESSON_PROGRESS_SUCCESS =
  'GET_ALL_LESSON_PROGRESS_SUCCESS';
export const GET_ALL_LESSON_PROGRESS_FAILED = 'GET_ALL_LESSON_PROGRESS_FAILED';
export const GET_LESSON_PROGRESS_SUCCESS = 'GET_LESSON_PROGRESS_SUCCESS';
export const GET_LESSON_PROGRESS_FAILED = 'GET_LESSON_PROGRESS_FAILED';
export const SAVE_LESSON_PROGRESS_SUCCESS = 'SAVE_LESSON_PROGRESS_SUCCESS';
export const SAVE_LESSON_PROGRESS_FAILED = 'SAVE_LESSON_PROGRESS_FAILED';
export const SAVE_QUIZ_SUCCESS = 'SAVE_QUIZ_SUCCESS';
export const SAVE_QUIZ_FAILED = 'SAVE_QUIZ_FAILED';
export const START_QUIZ_SUCCESS = 'START_QUIZ_SUCCESS';
export const START_QUIZ_FAILED = 'START_QUIZ_FAILED';
export const GET_QUIZ_RESULTS_SUCCESS = 'GET_QUIZ_RESULTS_SUCCESS';
export const GET_QUIZ_RESULTS_FAILED = 'GET_QUIZ_RESULTS_FAILED';

/*
* MANAGE TRAINING ACTIONS
*/
export const MANAGE_TRAINING_SUCCESS = 'MANAGE_TRAINING_SUCCESS';
export const MANAGE_TRAINING_FAILED = 'MANAGE_TRAINING_FAILED';
export const MANAGE_TRAINING_TOTAL_PAGES = 'MANAGE_TRAINING_TOTAL_PAGES';
export const SET_TABLE_FILTER_MANAGE_TRAINING =
  'SET_TABLE_FILTER_MANAGE_TRAINING';

/*
* MANAGE MEASUREMENTS ACTIONS
*/
export const MANAGE_MEASUREMENT_POINT_LISTS_SUCCESS =
  'MANAGE_MEASUREMENT_POINT_LISTS_SUCCESS';
export const MANAGE_MEASUREMENT_POINT_LISTS_FAILED =
  'MANAGE_MEASUREMENT_POINT_LISTS_FAILED';
export const MANAGE_MEASUREMENT_POINT_LISTS_TOTAL_PAGES =
  'MANAGE_MEASUREMENT_POINT_LISTS_TOTAL_PAGES';
export const SET_TABLE_FILTER_MANAGE_MEASUREMENT_POINT_LISTS =
  'SET_TABLE_FILTER_MANAGE_MEASUREMENT_POINT_LISTS';
export const MEASUREMENT_POINT_LIST_SUCCESS = 'MEASUREMENT_POINT_LIST_SUCCESS';
export const MEASUREMENT_POINT_LIST_FAILED = 'MEASUREMENT_POINT_LIST_FAILED';

export const MANAGE_MEASUREMENT_POINT_LIST_ADD =
  'MANAGE_MEASUREMENT_POINT_LIST_ADD';
export const MANAGE_MEASUREMENT_POINT_LIST_ADD_FAILED =
  'MANAGE_MEASUREMENT_POINT_LIST_ADD_FAILED';
export const MANAGE_MEASUREMENT_POINT_LIST_UPDATE =
  'MANAGE_MEASUREMENT_POINT_LIST_UPDATE';
export const MANAGE_MEASUREMENT_POINT_LIST_UPDATE_FAILED =
  'MANAGE_MEASUREMENT_POINT_LIST_UPDATE_FAILED';
export const MANAGE_MEASUREMENT_POINT_LIST_DELETE_SUCCESS =
  'MANAGE_MEASUREMENT_POINT_LIST_DELETE_SUCCESS';
export const MANAGE_MEASUREMENT_POINT_LIST_DELETE_FAILED =
  'MANAGE_MEASUREMENT_POINT_LIST_DELETE_FAILED';

export const TOGGLE_MODAL_EDIT_MEASUREMENT_POINT_LISTS =
  'TOGGLE_MODAL_EDIT_MEASUREMENT_POINT_LISTS';
export const TOGGLE_MODAL_EDIT_MEASUREMENT_POINT =
  'TOGGLE_MODAL_EDIT_MEASUREMENT_POINT';

export const MANAGE_MEASUREMENT_POINT_SAVE_TO_LIST =
  'MANAGE_MEASUREMENT_POINT_SAVE_TO_LIST';
export const SELECT_MEASUREMENT_POINT_LIST = 'SELECT_MEASUREMENT_POINT_LIST';
export const MANAGE_MEASUREMENT_POINT_SET_SELECTED_TAB =
  'MANAGE_MEASUREMENT_POINT_SET_SELECTED_TAB';
export const MANAGE_MEASUREMENT_POINT_UPDATE =
  'MANAGE_MEASUREMENT_POINT_UPDATE';
export const TOGGLE_MODAL_EDIT_MEASUREMENT_POINT_TAB =
  'TOGGLE_MODAL_EDIT_MEASUREMENT_POINT_TAB';
export const TOGGLE_MODAL_EDIT_MEASUREMENT_POINT_LIST_TEST_PROCEDURES =
  'TOGGLE_MODAL_EDIT_MEASUREMENT_POINT_LIST_TEST_PROCEDURES';
export const MANAGE_MEASUREMENT_POINT_TAB_UPDATE =
  'MANAGE_MEASUREMENT_POINT_TAB_UPDATE';
export const MANAGE_MEASUREMENT_POINT_LISTS_DELETE_SUCCESS =
  'MANAGE_MEASUREMENT_POINT_LISTS_DELETE_SUCCESS';
export const MANAGE_MEASUREMENT_POINT_LISTS_DELETE_FAILED =
  'MANAGE_MEASUREMENT_POINT_LISTS_DELETE_FAILED';

// MEASUREMENT POINT RESULTS
export const ADD_MEASUREMENT_POINT_RESULT = 'ADD_MEASUREMENT_POINT_RESULT';
export const UPDATE_MEASUREMENT_POINT_RESULT =
  'UPDATE_MEASUREMENT_POINT_RESULT';
export const GET_MEASUREMENT_POINT_FACILITY_RESULTS_SUCCESS =
  'GET_MEASUREMENT_POINT_FACILITY_RESULTS_SUCCESS';
export const GET_MEASUREMENT_POINT_FACILITY_RESULTS_FAILED =
  'GET_MEASUREMENT_POINT_FACILITY_RESULTS_FAILED';
export const RESET_MEASUREMENT_POINT_RESULT = 'RESET_MEASUREMENT_POINT_RESULT';
export const REMOVE_NOT_TESTED = 'REMOVE_NOT_TESTED';
export const SET_NOT_TESTED = 'SET_NOT_TESTED';
export const TOGGLE_MODAL_TEST_PROCEDURES = 'TOGGLE_MODAL_TEST_PROCEDURES';
export const SET_HISTORICAL_RESULT_ID = 'SET_HISTORICAL_RESULT_ID';
export const CLEAR_HISTORICAL_RESULT_ID = 'CLEAR_HISTORICAL_RESULT_ID';
export const SET_PREVIOUS_RESULT = 'SET_PREVIOUS_RESULT';
export const RESET_PREVIOUS_RESULT = 'RESET_PREVIOUS_RESULT';

/*
* MANAGE REPORT
*/
export const REPORT_MANAGE_GET_DEFAULT_SUCCESS =
  'REPORT_MANAGE_GET_DEFAULT_SUCCESS';
export const REPORT_MANAGE_GET_DEFAULT_FAILED =
  'REPORT_MANAGE_GET_DEFAULT_FAILED';
export const REPORT_UPDATE = 'REPORT_UPDATE';
// export const REPORT_UPDATE_SUCCESS = 'REPORT_UPDATE_SUCCESS';
// export const REPORT_UPDATE_FAILED = 'REPORT_UPDATE_FAILED';
export const REPORT_ADD_SUCCESS = 'REPORT_ADD_SUCCESS';
export const REPORT_ADD_FAILED = 'REPORT_ADD_FAILED';
export const REPORT_MANAGE_TOTAL_PAGES = 'REPORT_MANAGE_TOTAL_PAGES';
export const SET_TABLE_FILTER_MANAGE_REPORT = 'SET_TABLE_FILTER_MANAGE_REPORT';
export const TOGGLE_MODAL_EDIT_REPORT = 'TOGGLE_MODAL_EDIT_REPORT';
export const SET_SELECTED_REPORT = 'SET_SELECTED_REPORT';
export const SET_SELECTED_DEFAULT_REPORT_ID = 'SET_SELECTED_DEFAULT_REPORT_ID';
export const CLEAR_SELECTED_DEFAULT_REPORT_ID =
  'CLEAR_SELECTED_DEFAULT_REPORT_ID';
// brands
export const LOAD_BRANDS_SUCCESS = 'LOAD_BRANDS_SUCCESS';
export const ADD_BRAND_SUCCESS = 'ADD_BRAND_SUCCESS';
export const EDIT_BRAND_SUCCESS = 'EDIT_BRAND_SUCCESS';
export const REMOVE_BRAND_SUCCESS = 'REMOVE_BRAND_SUCCESS';

export const ADD_BRAND_FAILED = 'ADD_BRAND_FAILED';
export const EDIT_BRAND_FAILED = 'EDIT_BRAND_FAILED';
export const REMOVE_BRAND_FAILED = 'REMOVE_BRAND_FAILED';

export const TOGGLE_MODAL_EDIT_BRAND = 'TOGGLE_MODAL_EDIT_BRAND';
export const SET_TABLE_FILTER_MANAGE_BRAND = 'SET_TABLE_FILTER_MANAGE_BRAND';
export const BRAND_MANAGE_TOTAL_PAGES = 'BRAND_MANAGE_TOTAL_PAGES';
export const SET_SELECTED_BRAND_ID = 'SET_SELECTED_BRAND_ID';
export const CLEAR_SELECTED_BRAND_ID = 'CLEAR_SELECTED_BRAND_ID';

// manage customer and facility
export const GET_CUSTOMERS_AND_FACILITY_SUCCESS =
  'GET_CUSTOMERS_AND_FACILITY_SUCCESS';
export const GET_CUSTOMERS_AND_FACILITY_FAILED =
  'GET_CUSTOMERS_AND_FACILITY_FAILED';
export const CUSTOMERS_AND_FACILITY_TOTAL_PAGES =
  'CUSTOMERS_AND_FACILITY_TOTAL_PAGES';
export const ADD_CUSTOMERS_AND_FACILITY_SUCCESS =
  'ADD_CUSTOMERS_AND_FACILITY_SUCCESS';
export const EDIT_CUSTOMERS_AND_FACILITY_SUCCESS =
  'EDIT_CUSTOMERS_AND_FACILITY_SUCCESS';
export const SET_SELECTED_CUSTOMER_ID = 'SET_SELECTED_CUSTOMER_ID';
export const CLEAR_SELECTED_CUSTOMER_ID = 'CLEAR_SELECTED_CUSTOMER_ID';
export const FILTER_VISIBLE_CUSTOMERS = 'FILTER_VISIBLE_CUSTOMERS';

export const SET_SELECTED_FACILITY_ID = 'SET_SELECTED_FACILITY_ID';
export const CLEAR_SELECTED_FACILITY_ID = 'CLEAR_SELECTED_FACILITY_ID';
export const SET_TABLE_FILTER_MANAGE_CUSTOMER_AND_FACILITY =
  'SET_TABLE_FILTER_MANAGE_CUSTOMER_AND_FACILITY';
export const UPDATE_FORM_VALUES_MANAGE_CUSTOMER =
  'UPDATE_FORM_VALUES_MANAGE_CUSTOMER';
export const SET_FORM_VALUES_MANAGE_CUSTOMER =
  'SET_FORM_VALUES_MANAGE_CUSTOMER';
export const UPDATE_FORM_VALUES_MANAGE_FACILITY =
  'UPDATE_FORM_VALUES_MANAGE_FACILITY';
export const SET_FORM_VALUES_MANAGE_FACILITY =
  'SET_FORM_VALUES_MANAGE_FACILITY';
