export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED';

export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';

export const USER_QUEUE_SUCCESS = 'USER_QUEUE_SUCCESS';
export const USER_QUEUE_FAILED = 'USER_QUEUE_FAILED';

export const AAD_LOGIN_ = 'AAD_LOGIN';
export const AAD_LOGOUT_SUCCESS = 'AAD_LOGOUT_SUCCESS';
export const AAD_LOGIN = 'AAD_LOGIN';
export const AAD_LOGOUT_FAILED = 'AAD_LOGOUT_FAILED';

export const SET_REDIRECT_REFERRER = 'SET_REDIRECT_REFERRER';
export const REMOVE_REDIRECT_REFERRER = 'REMOVE_REDIRECT_REFERRER';

export const SET_REDIRECT_PATHNAME = 'SET_REDIRECT_PATHNAME';
export const REMOVE_REDIRECT_PATHNAME = 'REMOVE_REDIRECT_PATHNAME';

export const USER_APPROVE_SUCCESS = 'USER_APPROVE_SUCCESS';
export const USER_APPROVE_FAILED = 'USER_APPROVE_FAILED';

export const USER_REJECT_SUCCESS = 'USER_APPROVE_SUCCESS';
export const USER_REJECT_FAILED = 'USER_APPROVE_FAILED';

export const USER_QUEUE_UPDATE_SUCCESS = 'USER_QUEUE_UPDATE_SUCCESS';
export const USER_QUEUE_UPDATE_FAILED = 'USER_QUEUE_UPDATE_FAILED';

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';

export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAILED = 'USER_UPDATE_PROFILE_FAILED';

export const USER_QUEUE_INCREMENT = 'USER_QUEUE_INCREMENT';
export const USER_QUEUE_DECREMENT = 'USER_QUEUE_DECREMENT';

export const USER_QUEUE_TOTAL_PAGES = 'USER_QUEUE_TOTAL_PAGES';

export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_FAILED = 'GET_CUSTOMERS_FAILED';

export const GET_FACILITIES_SUCCESS = 'GET_FACILITIES_SUCCESS';
export const GET_FACILITIES_FAILED = 'GET_FACILITIES_FAILED';

export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_UPDATE_FAILED = 'CUSTOMER_UPDATE_FAILED';

export const FACILITY_UPDATE_SUCCESS = 'FACILITY_UPDATE_SUCCESS';
export const FACILITY_UPDATE_FAILED = 'FACILITY_UPDATE_FAILED';

export const CLOSE_ALL_MODALS = 'CLOSE_ALL_MODALS';
export const TOGGLE_MODAL_EDIT_QUEUE_USER = 'TOGGLE_MODAL_EDIT_QUEUE_USER';
export const TOGGLE_MODAL_EDIT_USER = 'TOGGLE_MODAL_EDIT_USER';
export const TOGGLE_MODAL_EDIT_CUSTOMER = 'TOGGLE_MODAL_EDIT_CUSTOMER';
export const TOGGLE_MODAL_EDIT_FACILITY = 'TOGGLE_MODAL_EDIT_FACILITY';
export const TOGGLE_MODAL_EDIT_PROFILE = 'TOGGLE_MODAL_EDIT_PROFILE';
export const TOGGLE_MODAL_SECURITY_FUNCTIONS =
  'TOGGLE_MODAL_SECURITY_FUNCTIONS';

export const USER_MANAGE_SUCCESS = 'USER_MANAGE_SUCCESS';
export const USER_MANAGE_FAILED = 'USER_MANAGE_FAILED';
export const USER_MANAGE_INCREMENT = 'USER_MANAGE_INCREMENT';
export const USER_MANAGE_DECREMENT = 'USER_MANAGE_DECREMENT';
export const USER_MANAGE_TOTAL_PAGES = 'USER_MANAGE_TOTAL_PAGES';

// TEAM
export const TEAM_MANAGE_SUCCESS = 'TEAM_MANAGE_SUCCESS';
export const TEAM_MANAGE_FAILED = 'TEAM_MANAGE_FAILED';
export const TEAM_MANAGE_INCREMENT = 'TEAM_MANAGE_INCREMENT';
export const TEAM_MANAGE_DECREMENT = 'TEAM_MANAGE_DECREMENT';
export const TEAM_MANAGE_TOTAL_PAGES = 'TEAM_MANAGE_TOTAL_PAGES';
export const TEAM_UPDATE_SUCCESS = 'TEAM_UPDATE_SUCCESS';
export const TEAM_UPDATE_FAILED = 'TEAM_UPDATE_FAILED';
export const TEAM_SAVE_SUCCESS = 'TEAM_SAVE_SUCCESS';
export const TEAM_SAVE_FAILED = 'TEAM_SAVE_FAILED';
export const TOGGLE_MODAL_EDIT_TEAM = 'TOGGLE_MODAL_EDIT_TEAM';

// inventory
export const GET_INVENTORY_SUCCESS = 'GET_INVENTORY_SUCCESS';
export const GET_INVENTORY_FAILED = 'GET_INVENTORY_FAILED';
export const INVENTORY_INCREMENT = 'INVENTORY_INCREMENT';
export const INVENTORY_DECREMENT = 'INVENTORY_DECREMENT';
export const INVENTORY_TOTAL_PAGES = 'INVENTORY_TOTAL_PAGES';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAILED = 'PRODUCT_UPDATE_FAILED';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAILED = 'PRODUCT_ADD_FAILED';
export const TOGGLE_MODAL_EDIT_PRODUCT = 'TOGGLE_MODAL_EDIT_PRODUCT';
export const GET_PRODUCT_INFO_SUCCESS = 'GET_PRODUCT_INFO_SUCCESS';
export const GET_PRODUCT_INFO_FAILED = 'GET_PRODUCT_INFO_FAILED';
export const SET_SELECTED_FACILITY = 'SET_SELECTED_FACILITY';
export const INSTALL_UPDATE_SUCCESS = 'INSTALL_UPDATE_SUCCESS';
export const INSTALL_UPDATE_FAILED = 'INSTALL_UPDATE_FAILED';
export const INSTALL_ADD_SUCCESS = 'INSTALL_ADD_SUCCESS';
export const INSTALL_ADD_FAILED = 'INSTALL_ADD_FAILED';
export const INSTALL_DELETE_SUCCESS = 'INSTALL_DELETE_SUCCESS';
export const INSTALL_DELETE_FAILED = 'INSTALL_DELETE_FAILED';
export const TOGGLE_MODAL_EDIT_INSTALL = 'TOGGLE_MODAL_EDIT_INSTALL';
export const SET_TABLE_FILTER_MANAGE_INVENTORY =
  'SET_TABLE_FILTER_MANAGE_INVENTORY';

// shopping cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const DECREASE_FROM_CART = 'DECREASE_FROM_CART';
export const UPDATE_QUANTITY_CART = 'UPDATE_QUANTITY_CART';

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILED = 'CHECKOUT_FAILED';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const TOGGLE_MODAL_EDIT_QUOTE = 'TOGGLE_MODAL_EDIT_QUOTE';
